version: "3"

services:
  postgres:
    container_name: contact-postgres
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=testing
      - POSTGRES_DB=contact_db
      - POSTGRES_HOST=localhost
    ports:
      - 5464:5432
