# Generated by Django 5.0.4 on 2024-04-22 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_control', '0004_alter_contact_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
